---
- name: install go
  include_role:
    name: gantsign.golang
- name: install apt-transport-https
  apt:
    name: apt-transport-https
- name: install build-essential
  apt:
    name: build-essential
    update_cache: yes
  become: true
- name: install git
  apt:
    name: git
    state: present
  become: true
- name: clone repository
  git:
    repo: https://github.com/chancoin-core/chancoin-cash.git
    dest: "{{ chancoin_install_path }}"
    accept_hostkey: yes
    version: "{{ chancoin_version }}"
- name: make sure chancoin install path exists
  file:
    path: "{{ chancoin_install_path}}"
    state: directory
  become: true
- name: make all chancoin
  shell: ./run_make.sh
  args:
    chdir: "{{ chancoin_install_path }}"
- name: copy chancoin to path
  shell: cp build/bin/chancoin /usr/bin/chancoin
  become: true
  args:
    chdir: "{{ chancoin_install_path }}"
- name: nuke the chain
  shell: rm -rf ~/.chancoin
  when: delete_chain|bool and really_delete_chain|bool
- name: init chain
  shell: "chancoin init {{ chancoin_network }}.json"
  args:
    chdir: "{{ chancoin_install_path }}"
# TODO Copy address file if it exists
- name: create chancoin service unit
  template:
    src: templates/chancoin.service
    dest: /etc/systemd/system/chancoin.service
  become: true
- name: enable chancoin unit
  shell: systemctl enable chancoin
  become: true
- name: start chancoin service
  service:
    name: chancoin
    state: started
  become: true
